#ifndef WHYSKO_INTENT_IDS_H
#define WHYSKO_INTENT_IDS_H


#define ACTOR_INTENT_UNDEFINED 0
#define ACTOR_INTENT_PLAYER_MOVE 5
#define ACTOR_INTENT_WAIT 10
#define ACTOR_INTENT_MOVE 11
#define ACTOR_INTENT_WORK 12


#endif//WHYSKO_INTENT_IDS_H
