#include "game_scene.h"


void GameScene::setup() {
    const int level[] =
            {
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    2,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    3,
                    0,
                    1,
                    0,
                    0,
                    2,
                    0,
                    3,
                    3,
                    3,
                    0,
                    1,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    0,
                    3,
                    3,
                    3,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    2,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    3,
                    0,
                    2,
                    2,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
                    2,
                    0,
                    2,
                    0,
                    1,
                    0,
                    3,
                    0,
                    2,
                    2,
                    2,
                    0,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    0,
                    0,
                    1,
                    0,
                    3,
                    2,
                    2,
                    2,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    1,
                    1,
            };

    map.setup(sf::Vector2u(32, 32), level, 16, 8);
}

void GameScene::think(float delta) {
    for (auto& actor: actors) {
        actor->think(delta);
    }
}

void GameScene::render(sf::RenderTarget& renderTarget) {
    renderTarget.draw(map);

    for (const auto& actor: actors) {
        actor->render(renderTarget);
    }
}

void GameScene::addActor(const std::shared_ptr<Actor>& actor) {
    actors.push_back(actor);
}
